# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "35d6afa3efd3967c37742a68a14a6520"
name = "Passionfruit Reviews Dev"
application_url = "https://examining-executives-tire-besides.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-3c08b97b.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://examining-executives-tire-besides.trycloudflare.com/auth/callback",
  "https://examining-executives-tire-besides.trycloudflare.com/auth/shopify/callback",
  "https://examining-executives-tire-besides.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[app_proxy]
url = "https://examining-executives-tire-besides.trycloudflare.com/api/storefront"
subpath = "passionfruit"
prefix = "apps"

[pos]
embedded = false
